[package]
name = "revolt-http"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde_json = "1"
revolt-models = { path = "../revolt-models" }
serde = "1"
thiserror = "1"
async-trait = "0"
