[package]
name = "revolt"
version = "0.1.0"
edition = "2021"

[dependencies]
revolt-models = { path = "../revolt-models" }
revolt-gateway = { path = "../revolt-gateway" }
revolt-http = { path = "../revolt-http" }
revolt-util = { path = "../revolt-util" }
