on: [push]

env:
  - CARGO_TERM_COLOR: always
  - RUSTDOCFLAGS: -Dwarnings

jobs:
  check:
    runs-on: docker
    container:
      image: rust
    steps:
      - uses: actions/checkout@v4

      - name: Add Rust components
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: Build project
        run: cargo check --quiet

      - name: Verify formatting
        run: cargo fmt --check --quiet

      - name: Verify lints
        run: cargo clippy --no-deps --quiet -- -Dwarnings

      - name: Verify documentation
        run: cargo doc --no-deps --quiet

      - name: Run tests
        run: cargo test --workspace --quiet
