[package]
name = "revolt-models"
version = "0.1.0"
edition = "2021"

[dependencies]
iso8601-timestamp = "0.1"
bitflags = "2.0.0-rc.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
