[package]
name = "rive"
version = "0.1.0"
edition = "2021"

[dependencies]
rive-models = { path = "../rive-models" }
rive-gateway = { path = "../rive-gateway" }
rive-http = { path = "../rive-http" }
rive-util = { path = "../rive-util" }
