[package]
name = "rive-http"
description = "Revolt REST API client for the Rive ecosystem."
categories = ["api-bindings"]
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords.workspace = true

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde_json = "1"
rive-models = { path = "../rive-models", version = "0.1.0" }
serde = "1"
thiserror = "1"
async-trait = "0"
