[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
revolt = { path = "../revolt" }

[[example]]
name = "ping-pong"
path = "ping-pong.rs"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
