[package]
name = "rive-gateway"
description = "Revolt WebSocket API implementaion for the Rive ecosystem."
categories = ["api-bindings"]
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords.workspace = true

[dependencies]
async-channel = { version = "1.8", default-features = false }
futures = { version = "0.3", default-features = false, features = ["std"] }
rive-models = { path = "../rive-models", version = "1", default-features = false }
serde_json = { version = "1", default-features = false, features = ["std"] }
thiserror = { version = "1", default-features = false }
tokio = { version = "1", default-features = false, features = ["macros", "rt", "time"] }
tokio-tungstenite = { version = "0.17", default-features = false, features = ["connect"] }

[features]
default = ["native-tls"]
native-tls = ["tokio-tungstenite/native-tls"]
rustls-tls-native-roots = ["tokio-tungstenite/rustls-tls-native-roots"]
rustls-tls-webpki-roots = ["tokio-tungstenite/rustls-tls-webpki-roots"]
