[package]
name = "rive-gateway"
description = "Revolt WebSocket API implementaion for the Rive ecosystem."
categories = ["api-bindings"]
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords.workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-webpki-roots"] }
rive-models = { path = "../rive-models", version = "0.1.1" }
serde_json = "1"
futures = "0.3"
thiserror = "1"
async-channel = "1.8"
